version: "3"
services:
    shishi-zekki-alert:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./src:/src
        tty: true
        restart: always
        command: /bin/bash -c "python main.py"
        environment:
            TZ: Asia/Tokyo
